name: "Render template from .env"
description: "Substitute S{VAR} environment variable placeholders in a template using a .env file"
inputs:
  template:
    description: "Path to the template  file"
    required: true
  envfile:
    description: "Path to the .env file"
    required: true
  output:
    description: "Path to the rendered output"
    required: true
runs:
  using: "composite"
  steps:

  
    - name: Run environment substitution
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh "${{ inputs.template }}" "${{ inputs.envfile }}" "${{ inputs.output }}"
